---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore(deps)'
    groups:
      npm-dependencies:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore(deps)'
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
