---
# Organization to pull metrics from
organization: 'UCL'

# Start date to pull metrics from
since: '2018-01-02'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/dashboard'
