---
# Organization to pull metrics from (must be an array)
organization: ['ucl', 'ucl-arc']

# Start date to pull metrics from
since: '2025-01-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/open-source-dashboard'
